<?php
/**
 * @var $this Mage_Adminhtml_Block_Notification_Toolbar
 */
?>

<?php $notice = Mage::helper('Mage_AdminNotification_Helper_Data')->getLatestNotice(); ?>
<?php if ($this->isShow()): ?>
<div class="notification-global" id="notification-<?php echo $notice->getId();?>">
    <?php
    $sParts = array();

    if ($this->getCriticalCount()):
        $sParts[] = '<span class="critical"><strong>'.$this->getCriticalCount().'</strong> '.$this->__('critical').'</span>';
    endif;

    if ($this->getMajorCount()):
        $sParts[] = '<strong>'.$this->getMajorCount().'</strong> '.$this->__('major');
    endif;

    if ($this->getMinorCount()):
        $sParts[] = '<strong>'.$this->getMinorCount().'</strong> '.$this->__('minor');
    endif;

    if ($this->getNoticeCount()):
        $sParts[] = '<strong>'.$this->getNoticeCount().'</strong> '.$this->__('notice');
    endif;

    $msgStats = '';
    $c = count($sParts);
    for ($i = 0; $i < $c; $i++) {
        $msgStats .= $sParts[$i] . ($i == $c-1 ? '' : ($i == $c-2 ? $this->__(' and ') : ', '));
    }

    $latestNoticeUrl = $this->getLatestNoticeUrl();
    ?>
    <?php /*
    <span class="f-right"><?php echo $this->__('You have %s unread message(s). <a href="%s">Go to messages inbox</a>.', $msgStats, $this->getNoticesInboxUrl());?></span>
    */?>

    <span class="f-right">
        <a class="close" href="#"><img src="<?php echo $this->getSkinUrl("images/bkg_btn-close2.gif"); ?>" /></a>
        <?php $goToBoxMessage = (!empty($latestNoticeUrl)) ? $this->__('Go to messages inbox') : $this->__('Go to notifications') ?>
        <?php echo $this->__('You have %s unread message(s).', $msgStats) ?> <a href="<?php echo $this->getNoticesInboxUrl() ?>"><?php echo $goToBoxMessage ?></a>
    </span>
    <?php /* ********** temporary commented
    <span class="f-right"><?php echo $this->__('You have %s, %s and %s unread messages. <a href="%s">Go to messages inbox</a>.', '<span class="critical"><strong>'.$this->getCriticalCount().'</strong> '.$this->__('critical').'</span>', '<strong>'.$this->getMajorCount().'</strong> '.$this->__('major'), '<strong>'.$this->getMinorCount().'</strong> '.$this->__('minor'), $this->getNoticesInboxUrl());?></span>
******** */?>
    <?php if ($this->isMessageWindowAvailable()): ?>
        <strong class="label clickable" onclick="openMessagePopup()">
    <?php else: ?>
        <strong class="label">
    <?php endif; ?>

    <?php echo $this->__('Latest Message:') ?></strong> <?php echo $this->getLatestNotice() ?>
    <?php if (!empty($latestNoticeUrl)): ?>
    <a href="<?php echo $this->escapeHtml($latestNoticeUrl) ?>" onclick="this.target='_blank';"><?php echo $this->__('Read details') ?></a>
    <?php endif; ?>
</div>
<?php endif; ?>



<script type="text/javascript">
    jQuery("a.close").click(function () {
        jQuery("#notification-<?php echo $notice->getNotificationId(); ?>").hide("slow");
        jQuery.get("<?php echo $this->getUrl("adminnotification/ajax/markAsRead", array("id"=>$notice->getNotificationId())); ?>", function (data) {
            if (data.status != "success")
            {
                jQuery("#notification-<?php echo $notice->getNotificationId(); ?>").show("slow", function() {
                    alert("Uh oh!  There was a problem marking that notification as read");
                });
            }
        })
    });

</script>